package com.superventas.pos.view.components;
import com.superventas.pos.view.FormProducto;
import java.awt.Dimension;
import javax.swing.ImageIcon;
/**
 *
 * @author Admin
 */
public class ProductosMenu extends javax.swing.JPanel {

    /**
     * Creates new form ProductosMenu
     */
    public ProductosMenu(Dimension tamaño) {
        initComponents();
        responsive(tamaño);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor_Principal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Botones = new javax.swing.JPanel();
        btn_NuevoProducto = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        btn_EliminarProducto = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        btn_ModificarProducto = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        btn_CategoriaProducto = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        Center = new javax.swing.JPanel();
        Separador = new javax.swing.JPanel();
        Title_CatalogoProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Contenedor_ShareBar = new javax.swing.JPanel();
        Share_Bar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        searchBar2 = new com.superventas.pos.view.components.SearchBar();
        jLabel3 = new javax.swing.JLabel();
        Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Contenedor_Principal.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor_Principal.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(41, 1, 138));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 900));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setOpaque(false);
        Header.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(20, 8, 72));
        jPanel5.setPreferredSize(new java.awt.Dimension(1240, 35));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCTO");
        jPanel5.add(jLabel1);

        Header.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        Botones.setOpaque(false);
        Botones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btn_NuevoProducto.setBackground(new java.awt.Color(168, 8, 72));
        btn_NuevoProducto.setBorder(null);
        btn_NuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_NuevoProducto.setText("Nuevo");
        btn_NuevoProducto.setFocusable(false);
        btn_NuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_NuevoProducto.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_NuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoProductoActionPerformed(evt);
            }
        });
        Botones.add(btn_NuevoProducto);

        btn_EliminarProducto.setBackground(new java.awt.Color(168, 8, 72));
        btn_EliminarProducto.setBorder(null);
        btn_EliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_EliminarProducto.setText("Eliminar");
        btn_EliminarProducto.setFocusable(false);
        btn_EliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_EliminarProducto.setPreferredSize(new java.awt.Dimension(150, 40));
        Botones.add(btn_EliminarProducto);

        btn_ModificarProducto.setBackground(new java.awt.Color(168, 8, 72));
        btn_ModificarProducto.setBorder(null);
        btn_ModificarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_ModificarProducto.setText("Modificar");
        btn_ModificarProducto.setFocusable(false);
        btn_ModificarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ModificarProducto.setPreferredSize(new java.awt.Dimension(150, 40));
        Botones.add(btn_ModificarProducto);

        btn_CategoriaProducto.setBackground(new java.awt.Color(168, 8, 72));
        btn_CategoriaProducto.setBorder(null);
        btn_CategoriaProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_CategoriaProducto.setText("Categoria");
        btn_CategoriaProducto.setFocusable(false);
        btn_CategoriaProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CategoriaProducto.setPreferredSize(new java.awt.Dimension(150, 40));
        Botones.add(btn_CategoriaProducto);

        Header.add(Botones, java.awt.BorderLayout.CENTER);

        jPanel1.add(Header, java.awt.BorderLayout.NORTH);

        Center.setOpaque(false);
        Center.setLayout(new java.awt.BorderLayout());

        Separador.setBackground(new java.awt.Color(255, 255, 255));
        Separador.setPreferredSize(new java.awt.Dimension(1240, 2));
        Separador.setRequestFocusEnabled(false);

        javax.swing.GroupLayout SeparadorLayout = new javax.swing.GroupLayout(Separador);
        Separador.setLayout(SeparadorLayout);
        SeparadorLayout.setHorizontalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        SeparadorLayout.setVerticalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Center.add(Separador, java.awt.BorderLayout.PAGE_START);

        Title_CatalogoProducto.setOpaque(false);
        Title_CatalogoProducto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CATALOGO DE PRODUCTOS");
        Title_CatalogoProducto.add(jLabel2);

        Center.add(Title_CatalogoProducto, java.awt.BorderLayout.CENTER);

        Contenedor_ShareBar.setOpaque(false);
        Contenedor_ShareBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 60, 0));

        Share_Bar.setOpaque(false);
        Share_Bar.setPreferredSize(new java.awt.Dimension(610, 50));
        Share_Bar.setLayout(new java.awt.BorderLayout());

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(550, 50));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        searchBar2.setForeground(new java.awt.Color(0, 0, 0));
        searchBar2.setText("searchBar2");
        searchBar2.setPreferredSize(new java.awt.Dimension(520, 40));
        searchBar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBar2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBar2FocusLost(evt);
            }
        });
        jPanel10.add(searchBar2);

        Share_Bar.add(jPanel10, java.awt.BorderLayout.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new ImageIcon("src\\main\\java\\com\\superventas\\pos\\img\\lupita-producto.png"));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 16));
        Share_Bar.add(jLabel3, java.awt.BorderLayout.WEST);

        Contenedor_ShareBar.add(Share_Bar);

        Center.add(Contenedor_ShareBar, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(Center, java.awt.BorderLayout.CENTER);

        Table.setOpaque(false);
        Table.setPreferredSize(new java.awt.Dimension(1240, 674));
        Table.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 600));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Nombre", "Descripcion", "Tipo Venta", "Precio Compra", "Ganacia", "Precio Venta", "Precio Mayoreo", "Impuesto", "Proveedor", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Table.add(jScrollPane1, new java.awt.GridBagConstraints());

        jPanel1.add(Table, java.awt.BorderLayout.SOUTH);

        Contenedor_Principal.add(jPanel1, new java.awt.GridBagConstraints());

        add(Contenedor_Principal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBar2FocusGained
        searchBar2.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBar2FocusGained

    private void searchBar2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBar2FocusLost
       searchBar2.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBar2FocusLost

    private void btn_NuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoProductoActionPerformed
        FormProducto fp = new FormProducto();
        fp.setVisible(true);
    }//GEN-LAST:event_btn_NuevoProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Contenedor_Principal;
    private javax.swing.JPanel Contenedor_ShareBar;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Separador;
    private javax.swing.JPanel Share_Bar;
    private javax.swing.JPanel Table;
    private javax.swing.JPanel Title_CatalogoProducto;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_CategoriaProducto;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_EliminarProducto;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_ModificarProducto;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_NuevoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.superventas.pos.view.components.SearchBar searchBar2;
    // End of variables declaration//GEN-END:variables
    private void responsive(Dimension tamaño){
        int xWidth = (int) (tamaño.getWidth()-20);
        int yHeitght = (int) (tamaño.getHeight()-20);
        Contenedor_Principal.setPreferredSize(tamaño);
        jPanel1.setPreferredSize(new Dimension(xWidth, yHeitght));
        Header.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.15)));
        Center.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.20)));
        Separador.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.15 *.02)));
        Title_CatalogoProducto.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.15 *.28)));
        Contenedor_ShareBar.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.15 *.68)));
        Table.setPreferredSize(new Dimension((int) xWidth, (int) (yHeitght * 0.65)));
        jScrollPane1.setPreferredSize(new Dimension((int) (xWidth*0.90) , (int) (yHeitght * 0.65 * 0.90)));
    }
}
