package com.superventas.pos.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author conta
 */
public class FormProducto extends javax.swing.JFrame {

    /**
     * Creates new form FormProductos
     */
    public FormProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorFormulario = new javax.swing.JPanel();
        LabelTOP = new javax.swing.JLabel();
        ContenedorCenter = new javax.swing.JPanel();
        foto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lbl_ImagenNuevoProducto = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        roundedButton1_Invoice1 = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        formulario = new javax.swing.JPanel();
        Parte1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_CodigoProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_NombreProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_DescripcionProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmb_TipoVentaProducto = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_PrecioCompraProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_PrecioMayoreoProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel8 = new javax.swing.JPanel();
        parte2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_GananciaProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_PrecioVentaProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_ImpuestoProducto = new com.superventas.pos.view.components.RoundedTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmb_ProveedorId = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmb_CategoriaId = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        ContenedorButtom = new javax.swing.JPanel();
        Button = new javax.swing.JPanel();
        btn_guardar = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        btn_limpiarCampos = new com.superventas.pos.view.components.RoundedButton1_Invoice();
        btn_volver = new com.superventas.pos.view.components.RoundedButton1_Invoice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorFormulario.setBackground(new java.awt.Color(41, 1, 138));
        ContenedorFormulario.setLayout(new java.awt.BorderLayout());

        LabelTOP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelTOP.setForeground(new java.awt.Color(255, 255, 255));
        LabelTOP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTOP.setText("Nuevo Producto");
        LabelTOP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        LabelTOP.setPreferredSize(new java.awt.Dimension(209, 60));
        ContenedorFormulario.add(LabelTOP, java.awt.BorderLayout.NORTH);

        ContenedorCenter.setOpaque(false);
        ContenedorCenter.setLayout(new java.awt.BorderLayout());

        foto.setOpaque(false);
        foto.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(41, 1, 138));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foto Producto");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 40));
        foto.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridBagLayout());

        lbl_ImagenNuevoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ImagenNuevoProducto.setIcon(new ImageIcon ("src/main/java/com/superventas/pos/img/ImgAggProducto.png"));
        lbl_ImagenNuevoProducto.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel17.add(lbl_ImagenNuevoProducto, new java.awt.GridBagConstraints());

        foto.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        roundedButton1_Invoice1.setBackground(new java.awt.Color(168, 8, 72));
        roundedButton1_Invoice1.setBorder(null);
        roundedButton1_Invoice1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1_Invoice1.setText("Seleccionar Imagen");
        roundedButton1_Invoice1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButton1_Invoice1.setPreferredSize(new java.awt.Dimension(200, 60));
        roundedButton1_Invoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1_Invoice1ActionPerformed(evt);
            }
        });
        jPanel18.add(roundedButton1_Invoice1, new java.awt.GridBagConstraints());

        foto.add(jPanel18, java.awt.BorderLayout.PAGE_END);

        ContenedorCenter.add(foto, java.awt.BorderLayout.CENTER);

        formulario.setOpaque(false);
        formulario.setPreferredSize(new java.awt.Dimension(700, 510));
        formulario.setLayout(new java.awt.BorderLayout());

        Parte1.setOpaque(false);
        Parte1.setPreferredSize(new java.awt.Dimension(350, 100));
        Parte1.setLayout(new java.awt.GridLayout(8, 1));

        jPanel1.setOpaque(false);
        Parte1.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        jPanel2.add(jLabel2);

        txt_CodigoProducto.setBorder(null);
        txt_CodigoProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.add(txt_CodigoProducto);

        Parte1.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3);

        txt_NombreProducto.setBorder(null);
        txt_NombreProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel3.add(txt_NombreProducto);

        Parte1.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion:");
        jPanel4.add(jLabel4);

        txt_DescripcionProducto.setBorder(null);
        txt_DescripcionProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.add(txt_DescripcionProducto);

        Parte1.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Venta:");
        jPanel5.add(jLabel5);

        cmb_TipoVentaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoVentaProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel5.add(cmb_TipoVentaProducto);

        Parte1.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Compra:");
        jPanel6.add(jLabel6);

        txt_PrecioCompraProducto.setBorder(null);
        txt_PrecioCompraProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel6.add(txt_PrecioCompraProducto);

        Parte1.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio Mayoreo:");
        jPanel7.add(jLabel7);

        txt_PrecioMayoreoProducto.setBorder(null);
        txt_PrecioMayoreoProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel7.add(txt_PrecioMayoreoProducto);

        Parte1.add(jPanel7);

        jPanel8.setOpaque(false);
        Parte1.add(jPanel8);

        formulario.add(Parte1, java.awt.BorderLayout.WEST);

        parte2.setOpaque(false);
        parte2.setLayout(new java.awt.GridLayout(8, 1));

        jPanel9.setOpaque(false);
        parte2.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ganancia % :");
        jPanel10.add(jLabel8);

        txt_GananciaProducto.setBorder(null);
        txt_GananciaProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel10.add(txt_GananciaProducto);

        parte2.add(jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio Venta:");
        jPanel11.add(jLabel9);

        txt_PrecioVentaProducto.setBorder(null);
        txt_PrecioVentaProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel11.add(txt_PrecioVentaProducto);

        parte2.add(jPanel11);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Impuesto:");
        jPanel12.add(jLabel10);

        txt_ImpuestoProducto.setBorder(null);
        txt_ImpuestoProducto.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel12.add(txt_ImpuestoProducto);

        parte2.add(jPanel12);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proveedor ID:");
        jPanel13.add(jLabel11);

        cmb_ProveedorId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_ProveedorId.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel13.add(cmb_ProveedorId);

        parte2.add(jPanel13);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Categoria ID:");
        jPanel14.add(jLabel12);

        cmb_CategoriaId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_CategoriaId.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel14.add(cmb_CategoriaId);

        parte2.add(jPanel14);

        jPanel15.setOpaque(false);
        parte2.add(jPanel15);

        jPanel16.setOpaque(false);
        parte2.add(jPanel16);

        formulario.add(parte2, java.awt.BorderLayout.CENTER);

        ContenedorCenter.add(formulario, java.awt.BorderLayout.WEST);

        ContenedorFormulario.add(ContenedorCenter, java.awt.BorderLayout.CENTER);

        ContenedorButtom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        ContenedorButtom.setOpaque(false);
        ContenedorButtom.setPreferredSize(new java.awt.Dimension(100, 130));
        ContenedorButtom.setLayout(new java.awt.GridBagLayout());

        Button.setOpaque(false);
        Button.setPreferredSize(new java.awt.Dimension(450, 80));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0);
        flowLayout1.setAlignOnBaseline(true);
        Button.setLayout(flowLayout1);

        btn_guardar.setBackground(new java.awt.Color(168, 8, 72));
        btn_guardar.setBorder(null);
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new ImageIcon
            ("src/main/java/com/superventas/pos/img/Save.png"));
        btn_guardar.setText("");
        btn_guardar.setFocusable(false);
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_guardar.setPreferredSize(new java.awt.Dimension(120, 80));
        Button.add(btn_guardar);

        btn_limpiarCampos.setBackground(new java.awt.Color(168, 8, 72));
        btn_limpiarCampos.setBorder(null);
        btn_limpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarCampos.setIcon(new ImageIcon("src/main/java/com/superventas/pos/img/Limpiar.png"));
        btn_limpiarCampos.setText("");
        btn_limpiarCampos.setFocusable(false);
        btn_limpiarCampos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_limpiarCampos.setPreferredSize(new java.awt.Dimension(120, 80));
        Button.add(btn_limpiarCampos);

        btn_volver.setBackground(new java.awt.Color(168, 8, 72));
        btn_volver.setBorder(null);
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setIcon(new ImageIcon("src/main/java/com/superventas/pos/img/Atras.png"));
        btn_volver.setText("");
        btn_volver.setFocusable(false);
        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_volver.setPreferredSize(new java.awt.Dimension(120, 80));
        Button.add(btn_volver);

        ContenedorButtom.add(Button, new java.awt.GridBagConstraints());

        ContenedorFormulario.add(ContenedorButtom, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ContenedorFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ContenedorFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButton1_Invoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1_Invoice1ActionPerformed
        String ruta = "";
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        file.setFileFilter(filtrado);

        int respuesta = file.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION){
            ruta = file.getSelectedFile().getPath();
            Image mImagen = new ImageIcon(ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(lbl_ImagenNuevoProducto.getWidth(), lbl_ImagenNuevoProducto.getHeight(), Image.SCALE_SMOOTH));
            lbl_ImagenNuevoProducto.setIcon(mIcono);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedButton1_Invoice1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button;
    private javax.swing.JPanel ContenedorButtom;
    private javax.swing.JPanel ContenedorCenter;
    private javax.swing.JPanel ContenedorFormulario;
    private javax.swing.JLabel LabelTOP;
    private javax.swing.JPanel Parte1;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_guardar;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_limpiarCampos;
    private com.superventas.pos.view.components.RoundedButton1_Invoice btn_volver;
    private javax.swing.JComboBox<String> cmb_CategoriaId;
    private javax.swing.JComboBox<String> cmb_ProveedorId;
    private javax.swing.JComboBox<String> cmb_TipoVentaProducto;
    private javax.swing.JPanel formulario;
    private javax.swing.JPanel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_ImagenNuevoProducto;
    private javax.swing.JPanel parte2;
    private com.superventas.pos.view.components.RoundedButton1_Invoice roundedButton1_Invoice1;
    private com.superventas.pos.view.components.RoundedTextField txt_CodigoProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_DescripcionProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_GananciaProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_ImpuestoProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_NombreProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_PrecioCompraProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_PrecioMayoreoProducto;
    private com.superventas.pos.view.components.RoundedTextField txt_PrecioVentaProducto;
    // End of variables declaration//GEN-END:variables
}
